server:
  port: 7779
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/demodb
    username: root
    password: a020328@j
    driver-class-name: com.mysql.cj.jdbc.Driver
  servlet:
    multipart:
      max-file-size: 2MB
      max-request-size: 5MB
mybatis-plus:
  configuration:
    # 日志
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      logic-delete-field: delFlag
      logic-delete-value: 1
      logic-not-delete-value: 0
      id-type: auto
      enum-type-handler: com.baomidou.mybatisplus.extension.handlers.MybatisEnumTypeHandler

